name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule: # run every hour
    - cron: '0 * * * *'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          persist-credentials: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Self Report Metrics
        id: self-report-metrics
        uses: ./
        with:
          junit-xml-folder: 'test-results'
          service-name: 'cae-otel-ci-visibility'
          service-namespace: 'redis'
          service-version: '1.0.0-dev'
          deployment-environment: 'ci'
          otlp-endpoint: 'https://otlp-gateway-prod-us-central-0.grafana.net/otlp/v1/metrics'
          otlp-headers:
            '{"Authorization": "Basic ${{
            secrets.SELF_CHECK_OTEL_AUTHORIZATION_TOKEN}}"}'
        env:
          OTEL_EXPORTER_OTLP_PROTOCOL: 'http/protobuf'
          ACTIONS_STEP_DEBUG: 'true'
          OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: 'BASE2_EXPONENTIAL_BUCKET_HISTOGRAM'
